create table tb_cs_comment
(
    id         bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp not null,
    status     varchar(255),
    text       clob,
    service_id bigint    not null,
    primary key (id)
);
create table tb_cs_service
(
    id          bigint generated by default as identity,
    created_at  timestamp not null,
    updated_at  timestamp not null,
    description varchar(255),
    title       varchar(255),
    primary key (id)
);
alter table tb_cs_comment
    add constraint FKiipp3aj4qviuer9lnvl1q713b foreign key (service_id) references tb_cs_service
